name: Build Arch/Manjaro Package


on:
  push:
    tags:
      - '*.*.*'


jobs:
  Build Google Chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          debug: true
          target: pkgbuild
          pkgname: google-chrome/

      - name: Create Arch package checksum file
        run:
          sudo chown -R $USER
          md5sum google-chrome/*.zst >> google-chrome/google-chrome-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum


  Build Huggle:
    runs-on: ubuntu-latest
    needs: [Build Google Chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          debug: true
          target: pkgbuild
          pkgname: huggle/

      - name: Create Arch package checksum file
        run:
          sudo chown -R $USER
          md5sum huggle/*.zst >> huggle/huggle-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum


  Build RStudio Desktop:
    runs-on: ubuntu-latest
    needs: [Build Huggle]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          debug: true
          target: pkgbuild
          pkgname: rstudio/

      - name: Create Arch package checksum file
        run:
          sudo chown -R $USER
          md5sum rstudio/*.zst >> rstudio/rstudio-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum


  Build Twine:
    runs-on: ubuntu-latest
    needs: [Build RStudio Desktop]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          debug: true
          target: pkgbuild
          pkgname: twinejs/

      - name: Create Arch package checksum file
        run:
          sudo chown -R $USER
          md5sum twinejs/*.zst >> twinejs/twinejs-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum
