name: Build Arch/Manjaro Package


on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:


jobs:
  Build_Google_Chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Download snapshot from  AUR
        run: git submodule update --init --recursive

      - name: Update snapshot to Latest commit
        run: git submodule update --remote --merge

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: nawan95/arch-pkgbuild-builder@aa501a7992891e08a85373966f4840abdd315945
        with:
          debug: true
          target: pkgbuild
          pkgname: google-chrome/

      - name: Create Arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum google-chrome/*.zst >> google-chrome/google-chrome-x86_64.pkg.tar.zst.md5sum

  Build_Huggle:
    runs-on: ubuntu-latest
    needs: [Build_Google_Chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Download snapshot from  AUR
        run: git submodule update --init --recursive

      - name: Update snapshot to Latest commit
        run: git submodule update --remote --merge

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: nawan95/arch-pkgbuild-builder@aa501a7992891e08a85373966f4840abdd315945
        with:
          debug: true
          target: pkgbuild
          pkgname: huggle/

      - name: Create Arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum huggle/*.zst >> huggle/huggle-x86_64.pkg.tar.zst.md5sum

  Build_RStudio_Desktop:
    runs-on: ubuntu-latest
    needs: [Build_Huggle]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Download snapshot from  AUR
        run: git submodule update --init --recursive

      - name: Update snapshot to Latest commit
        run: git submodule update --remote --merge

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: nawan95/arch-pkgbuild-builder@aa501a7992891e08a85373966f4840abdd315945
        with:
          debug: true
          target: pkgbuild
          pkgname: rstudio/

      - name: Create Arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum rstudio/*.zst >> rstudio/rstudio-x86_64.pkg.tar.zst.md5sum

  Build_Twine:
    runs-on: ubuntu-latest
    needs: [Build_RStudio_Desktop]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Download snapshot from  AUR
        run: git submodule update --init --recursive

      - name: Update snapshot to Latest commit
        run: git submodule update --remote --merge

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: nawan95/arch-pkgbuild-builder@aa501a7992891e08a85373966f4840abdd315945
        with:
          debug: true
          target: pkgbuild
          pkgname: twinejs/

      - name: Create Arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum twinejs/*.zst >> twinejs/twinejs-x86_64.pkg.tar.zst.md5sum

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build_Twine]

    steps:
      - name: Install and Build 🔧
        run: |
          sudo apt-get update
          sudo apt-get install curl git -y
          curl https://raw.githubusercontent.com/jayanta525/apindex-v2/master/sudo-install.sh | bash
          apindex .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .